import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideProps,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  ArrowLeftToLine,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  LucideIcon,
  Store,
  Warehouse,
  ShoppingBasket,
  ListCollapse,
  Truck,
  HandCoins,
  LayoutDashboard,
  MapPinned,
  Map,
  Handshake,
  Palette,
  Brush,
  Notebook,
  CircleX,
  RotateCcw,
  Mail,
  CircleCheck,
  SquareArrowRight,
  SquareArrowLeft,
  SunMoon,
  Upload,
  Eye,
  FilePenIcon,
  PackageOpenIcon,
  Bell,
  Package,
  Gauge,
  Building,
  Locate,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  back: ArrowLeftToLine,
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  store: Store,
  warehouse: Warehouse,
  shoppingBasket: ShoppingBasket,
  listCollapse: ListCollapse,
  truck: Truck,
  handCoins: HandCoins,
  layoutDashboard: LayoutDashboard,
  mapPinned: MapPinned,
  map: Map,
  handshake: Handshake,
  palette: Palette,
  brush: Brush,
  rol: Notebook,
  reset: RotateCcw,
  cancel: CircleX,
  mail: Mail,
  confirmation: CircleCheck,
  show: SquareArrowRight,
  colapse: SquareArrowLeft,
  check: Check,
  sunMoon: SunMoon,
  upload: Upload,
  eye: Eye,
  filePenIcon: FilePenIcon,
  packageOpenIcon: PackageOpenIcon,
  notification: Bell,
  package:Package,
  gauge:Gauge,
  building:Building,
  locate:Locate
}
